# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(null=True, to='home.Tag'),
        ),
    ]
